name: Tests #Nombre de mi accion

#me dice sobre que accion y ramas quiero realizar la accion
on:
  push:
    branches:
      - main


#definicion de los pasos de mi accion
jobs:
  run-tests: #nombre del trabajo
    runs-on: ubuntu-latest #entorno sobre el que lo quiero ejecutar
    steps:
      - name: Checkout #nombre del paso a ejecutar
        uses: actions/checkout@v2 #accion predefinida de git para hacer checkout en la VM
      - name: Jest Install #instalacion de jest en la vm
        run: npm install jest 
      - name: Jest run #Ejecucion de las pruebas
        run: npm test